### ISSUE TITLE
gclib/GThreads.h:804:19: error: conflicting declaration 'typedef long long int __intmax_t'

### ISSUE THREAD

**Issue by mmokrejs** [gpertea/stringtie#186]
Hi,
  seems stringtie does not compile with gcc-7.3.0. Would you mind inspecting the cause? Ideally, will it compile using gclib-0.10.2 installed system-wide?

```
In file included from gclib/GThreads.cpp:24:0:
gclib/GThreads.h:804:19: error: conflicting declaration 'typedef long long int __intmax_t'
 typedef long long __intmax_t;
                   ^~~~~~~~~~
In file included from /usr/include/bits/byteswap.h:27:0,
                 from /usr/include/endian.h:60,
                 from /usr/include/pthread.h:22,
                 from gclib/GThreads.h:99,
                 from gclib/GThreads.cpp:24:
/usr/include/bits/types.h:61:18: note: previous declaration as 'typedef long int __intmax_t'
 typedef long int __intmax_t;
                  ^~~~~~~~~~
make: *** [Makefile:112: gclib/GThreads.o] Error 1
```

[build.log](https://github.com/gpertea/stringtie/files/2134977/build.log)

**Comment by gpertea** [comment]
StringTie source code is meant to be self-contained and it uses its own dedicated private instance of [some of] the gclib source code. As discussed elsewhere, `gclib` should not be installed system-wide anyway (it's a source code library, not a real binary object library).
I have been building stringtie  (the master branch here and the "official" release package at http://ccb.jhu.edu/software/stringtie/#install) with various gcc versions (from v4.x to v8.1.1) and haven't seen this error. I cannot even find that kind of declaration at GThreads.h:804, even in the 0.10.2 tagged version..

**Comment by mmokrejs** [comment]
Weird. I get the source tarball from https://github.com/gentoo/sci/blob/be33780bc70d6cc463c236d5e2ceb2273170c191/sci-biology/stringtie/stringtie-1.2.2.ebuild#L9 which shoud be http://ccb.jhu.edu/software/stringtie/dl/stringtie-1.2.2.tar.gz . Checksum is here https://github.com/gentoo/sci/blob/master/sci-biology/stringtie/Manifest

**Comment by gpertea** [comment]
Not sure why such an old and potentially buggy version of stringtie is being referenced here.. The current link to the "official" source release is http://ccb.jhu.edu/software/stringtie/dl/stringtie-1.3.4d.tar.gz as seen on the official web page.. It is also tagged accordingly in this github repository -- which, as opposed to my other projects using gclib, is fully self-contained (it has its own instance of gclib source files) and should not depend on any other packages or repositories.
